from abc import ABC, abstractmethod
from typing import List
from airbnb_lab2.app.models.entities import User, Housing, Booking, Payment

class IUserDAO(ABC):
    @abstractmethod
    def add_user(self, user: User): ...
    @abstractmethod
    def get_all_users(self) -> List[User]: ...
    @abstractmethod
    def load_from_csv(self, file_path: str): ...

class IHousingDAO(ABC):
    @abstractmethod
    def add_housing(self, housing: Housing): ...
    @abstractmethod
    def get_all_housing(self) -> List[Housing]: ...
    @abstractmethod
    def load_from_csv(self, file_path: str): ...

class IBookingDAO(ABC):
    @abstractmethod
    def add_booking(self, booking: Booking): ...
    @abstractmethod
    def get_all_bookings(self) -> List[Booking]: ...
    @abstractmethod
    def load_from_csv(self, file_path: str): ...

class IPaymentDAO(ABC):
    @abstractmethod
    def add_payment(self, payment: Payment): ...
    @abstractmethod
    def get_all_payments(self) -> List[Payment]: ...
    @abstractmethod
    def load_from_csv(self, file_path: str): ...